name = "Vimes"
uuid = "85f4b15a-ac2e-11e8-1659-abc63ef75ab0"
authors = ["Mike J Innes <mike.j.innes@gmail.com>"]
version = "0.1.1-DEV"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SourceWalk = "2987fe4f-acca-4bd1-87ee-98b3d562f1a1"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
MacroTools = "0.1, 0.2, 0.3, 0.4, 0.5"
SourceWalk = "0.1"
StatsBase = "0.25, 0.26, 0.27, 0.28, 0.29, 0.30, 0.31, 0.32"
julia = "1"

[extras]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Pkg", "Test"]
